### ISSUE TITLE
customer group not updated after subscriber email is used for customer registration

### ISSUE THREAD

**Issue by jhruehl** [mailchimp/mc-magento#677] opened 2018-04-03 08:21 UTC
If a subscriber uses the same email for a customer registration the first and last name is synced, but at least the merge var 'Group' (Customer Group) isn't.

### Preconditions
1. Magento 1.14.3.8 Commerce
2. Mailchimp extension with ecommerce sync enabled and merge vars (including customer group) used

### Steps to reproduce
1. Sign up with an unregistered email address for the Magento newsletter
2. Use the same email address to register a customer account
3. Look up the email address in the linked Mailchimp list

### Expected result
1. All new avaible merge var data from the new customer account is synced after the account registration process
2. Given 1. the customer group is updated from 'NOT LOGGED IN' to 'General'

### Actual result
1. Only first and last name is synced
2. Customer Group is still 'NOT LOGGED IN'

### Additional testing results
If I save the newsletter subscriptions in the Magento 1 frontend customer account again, the subscriber is marked as modified by the Mailchimp extension and the customer group is correctly synced.

### Guessed Cause
The merge var functionality doesn't work in a correct way or isn't used at all, if a customer is synced via the ecommerce functionality of the Mailchimp extension. I didn't have a closer look at the code, but preconfigured merge vars should be synched for customers as well or shouldn't they?

**Comment by jhruehl** [comment] 2018-04-16 06:41
@Santiagoebizmarts Any update? This is quite important for our customer.

**Comment by ebizmarts-keller** [comment] 2018-08-09 13:32
Hello @jhruehl 

I have just tested this on Magento 1.9.3.9 and Mailchimp for Magento 1.1.12, and I could not reproduce the issue.

I used the following steps:

1. Sign up with an unregistered email address for the Magento newsletter
2. Use the same email address to register a customer account
3. Look up the email address in the linked Mailchimp list

The customer group (CGROUP) is saved as 'NOT LOGGED IN', this is correct (and should remain only for a few minutes) since the subscriber was synced instantly with that customer group, and the customer was created afterwards.

At the moment the email is subscribed, an entry is added to the newsletter_subscriber table, with a mailchimp_sync_delta (time it was synced).

The moment you register an account using that same email, the mailchimp_sync_modified value for that row in newsletter_subscriber changes to 1 (this means it is marked to be updated by cron).

Then when the cronjob runs (mailchimp_bulksync_subscriber_data), the subscriber is updated with the proper mergefield values (I tested with the CGROUP and was updated to 'General').

If you still have this issue try with the latest version of the extension and make sure the cronjob is running every 5 minutes without errors, I will close the issue for now since I cannot reproduce it with the steps you provided.

**Closed by ebizmarts-keller** 2018-08-09 13:32 UTC
