### ISSUE TITLE
Upgrade to 1.1.2 : You cannot define a correlation name 'mc' more than once

### ISSUE THREAD

**Issue by seansan** [mailchimp/mc-magento#725] opened 2018-06-04 13:42 UTC
Upgrade to 1.1.2 from 1.1.11

You cannot define a correlation name 'mc' more than once

Trace:
#0 lib/Varien/Db/Select.php(281): Zend_Db_Select->_join('left join', Array, 'mc.related_id=m...', Array, NULL)
#1 app/code/core/Zend/Db/Select.php(373): Varien_Db_Select->_join('left join', Array, 'mc.related_id=m...', Array, NULL)
#2 app/code/community/Ebizmarts/MailChimp/Model/Observer.php(506): Zend_Db_Select->joinLeft(Array, 'mc.related_id=m...', Array)
#3 app/code/core/Mage/Core/Model/App.php(1360): Ebizmarts_MailChimp_Model_Observer->addColumnToSalesOrderGridCollection(Object(Varien_Event_Observer))
#4 app/code/core/Mage/Core/Model/App.php(1333): Mage_Core_Model_App->_callObserverMethod(Object(Ebizmarts_MailChimp_Model_Observer), 'addColumnToSale...', Object(Varien_Event_Observer))
#5 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('sales_order_gri...', Array)
#6 app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(589): Mage::dispatchEvent('sales_order_gri...', Array)
#7 lib/Varien/Data/Collection/Db.php(565): Mage_Core_Model_Resource_Db_Collection_Abstract->_beforeLoad()
#8 lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#9 app/design/adminhtml/default/default/template/bl/customgrid/widget/grid/16.phtml(194): Varien_Data_Collection->getIterator()
#10 app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/s...')
#11 app/code/core/Mage/Core/Block/Template.php(273): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#12 app/code/core/Mage/Core/Block/Template.php(287): Mage_Core_Block_Template->renderView()
#13 app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#14 app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#15 app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#16 app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('grid', true)
#17 app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(77): Mage_Core_Block_Abstract->getChildHtml('grid')
#18 app/design/adminhtml/default/default/template/widget/grid/container.phtml(36): Mage_Adminhtml_Block_Widget_Grid_Container->getGridHtml()
#19 app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/s...')
#20 app/code/core/Mage/Core/Block/Template.php(273): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#21 app/code/core/Mage/Core/Block/Template.php(287): Mage_Core_Block_Template->renderView()
#22 app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#23 app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#24 app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#25 app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#26 app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
#27 app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#28 app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#29 app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#30 app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/s...')
#31 app/code/core/Mage/Core/Block/Template.php(273): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#32 app/code/core/Mage/Core/Block/Template.php(287): Mage_Core_Block_Template->renderView()
#33 app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#34 app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#35 app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#36 app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#37 app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(95): Mage_Core_Controller_Varien_Action->renderLayout()
#38 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_OrderController->indexAction()
#39 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#40 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#41 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#42 app/Mage.php(683): Mage_Core_Model_App->run(Array)
#43 index.php(88): Mage::run('STORE', 'store')

**Comment by Santiagoebizmarts** [comment] 2018-06-04 17:05
Hello @seansan 

Please add more information in order to allow us to try to replicate this.

Regards.

**Comment by seansan** [comment] 2018-06-04 17:06
You cant just close issues

**Comment by Santiagoebizmarts** [comment] 2018-06-04 17:43
I will re-open if we get to the cause of this and it is related to the extension. That is why we have the template suggesting the information that is required to replicate issues.
There is nothing there stating what is happening that triggers that error.

**Comment by seansan** [comment] 2018-06-04 17:58
​​
​no I am reporting the error

(could also not do that)

If I knew the solution I would fix it myself

If you leave the issue open then the community can *contribute*

Maybe someone has seen the issue before: but if you close it nobody will
every see it

And it makes it look like there is no issue

​

**Comment by seansan** [comment] 2018-06-04 17:59
​​
​The error is here

changing mc to  mchimp does not solve the issue (and rules out most other
extensions, unless the both use MC and MCHIMP)

    public function
addColumnToSalesOrderGridCollection(Varien_Event_Observer $observer)
    {

        $helper = $this->makeHelper();
        $addColumnConfig = $helper->getMonkeyInGrid(0);
        $ecommEnabledAnyScope = $helper->isEcomSyncDataEnabledInAnyScope();
        if ($ecommEnabledAnyScope && $addColumnConfig && false) {
            $collection = $observer->getOrderGridCollection();
            $collection->addFilterToMap('store_id', 'main_table.store_id');
            $select = $collection->getSelect();
            $adapter =
$this->getCoreResource()->getConnection('core_write');
            $select->joinLeft(array('mchimp' =>
$collection->getTable('mailchimp/ecommercesyncdata')),
$adapter->quoteInto('mchimp.related_id=main_table.entity_id AND type = ?',
Ebizmarts_MailChimp_Model_Config::IS_ORDER),
array('mchimp.mailchimp_synced_flag', 'mchimp.id'));
            $select->group("main_table.entity_id");
            $direction = $this->getRegistry();
            if ($direction) {
                $collection->addOrder('mchimp.id', $direction);
                $this->removeRegistry();
            }
        }
    }​

**Comment by Santiagoebizmarts** [comment] 2018-06-04 18:40
@seansan 
For these kind of contributions we have our [forums](https://ebizmarts.com/forums/view/6)
The idea of issues is to report a particular problem and what triggered it.
We expect something like this: "When I go to the order grid and filter by xxxx value..."
I mean something to allow us to replicate the issue, not a solution. Of course solutions are welcome as well.

Looking at the code you pasted above I see there false condition in the if causing it to never really access that if.
You can see [HERE](https://github.com/mailchimp/mc-magento/blob/1.1.12/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L501) there is no if at the end of the conditions.

Regards.

**Comment by seansan** [comment] 2018-06-04 20:30
We added false to circumvent the error and at least use it

And how it was triggered. That was written on line 1

We upgraded

I think it is very clear

You should not just close issues

**Comment by Santiagoebizmarts** [comment] 2018-06-04 20:46
@seansan We cannot keep every particular situation open just in case. We need to have the ability to replicate or solve the problem otherwise it will get very hard to keep track of the issues to solve.
This is a free extension with thousands of users.
You can post this same issue in the [forum](https://ebizmarts.com/forums/view/6) and it will not be closed. There people can help into finding the problem/solution and finally create an issue for it if there is something needed to be changed in the extension.

Regards.

**Comment by view6com** [comment] 2018-07-03 12:37
Thanks @seansan updating line 501 (app/code/community/Ebizmarts/MailChimp/Model/Observer.php) with && false got around this admin error for us, so it ends up like this:

if ($ecommEnabledAnyScope && $addColumnConfig && false) {

Thanks again.

**Comment by seansan** [comment] 2018-07-03 12:41
Thx 
TBH it is a stupid fix, but it works 

I needed to share as long as tickets get closed so fast here ....

**Comment by Santiagoebizmarts** [comment] 2018-07-03 12:56
Hello @seansan @view6com 
You can see a fix for this at https://github.com/mailchimp/mc-magento/issues/732#issuecomment-401837602
It will be added soon and will be referenced to this issue as well as the #732 
@sukiman was kind enough to help in this matter.

Regards.

**Closed** 2018-07-19 18:59 UTC
Labels: bug
