### ISSUE TITLE
Infinite loop (?), eventually an PHP out of memory error when adding a new subscriber

### ISSUE THREAD

**Issue by durzel** [mailchimp/mc-magento#276] opened 2017-05-29 20:28 UTC
I'm trying to migrate from MageMonkey 1.2.10 to Mailchimp for Magento 1.1.6.  I've removed the old extension successfully, and deleted the obsolete tables, etc.  I've had no problems installing the new extension.

After configuring the extension with my API key (at a store level), I am unable to subscribe any new email address to the specified list from the frontend of the website (a simple default email only subscribe form).  When I try, the browser just "connects" endlessly before eventually timing out, showing a blank white screen with 500 Internal Server Error code, on page /newsletter/subscribe/new (I think?)

In the webserver logs I see the following:

```
[Mon May 29 18:32:41.185310 2017] [:error] [pid 58454] [client 1.2.3.4:51884] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 36864 bytes) in /home/magento/.modman/mc-magento/lib/Ebizmarts/Mailchimp.php on line 273, referer: https://www.magento-site.com/
[Mon May 29 18:40:06.667847 2017] [:error] [pid 57310] [client 1.2.3.4:51971] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /home/magento/.modman/mc-magento/lib/Ebizmarts/Mailchimp.php on line 273, referer: https://www.magento-site.com/
```
(increasing the PHP max memory to 512MB made no difference)

In exception.log I see an error along the lines of the following:

`Warning: Error while sending QUERY packet. PID=12345`

I'm a bit lost as to how to debug this as it seems like a catastrophic issue that no one else has reported?  I guess it's related to CURL in some way, since that's what the code near to line 273 in Mailchimp.php is using.

Any thoughts?

If it matters - I'm using PHP 7.0.18 on Magento CE 1.9.3.2.  Everything else in Magento is working fine.  Removing Mailchimp for Magento and going back to MageMonkey 1.2.10 immediately fixed the problem.

**Comment by durzel** [comment] 2017-05-29 20:58
To add - e-commerce is not currently enabled (I'm aware of high resource use bug when it is), and the only MySQL query that the newsletter subscription does is to query sales_flat_order for the supplied email address (why it does that I don't know). 

Running that query in isolation completes instantly so I don't think it's a MySQL issue.

**Comment by elluminatte** [comment] 2017-05-31 12:08
hi there.
got the same issue as issue starter:
```
PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /home/budsies/www/lib/Ebizmarts/Mailchimp.php on line 273
```

**Comment by elluminatte** [comment] 2017-06-01 08:56
Hello guys.

Figured out a possible reason of discussing problem. It's caused by update of **Ebizmarts_MailChimp_Model_Api_Subscribers.updateSubscriber()** method in 1.1.6 version: when Mailchimp API returns error (http code >= 400) and subscriber's status is not **"subscribed"** we got an endless loop.

Let's explore this within fake e-mail subscription attempt case (for example - test@example.com). I'll attach screenshots of workflow debugging process for transparency.

I come to **Ebizmarts_MailChimp_Model_Observer.handleSubscriber()** method and going to **Ebizmarts_MailChimp_Model_Api_Subscribers.updateSubscriber()**.

![1](https://cloud.githubusercontent.com/assets/8599788/26671231/642d199a-46bd-11e7-9150-86350a18c59a.png)

Because of fake e-mail i got 400 error from Mailchimp API and **Mailchimp_Error** exception in API **Ebizmarts_Mailchimp.call()** method

![2](https://cloud.githubusercontent.com/assets/8599788/26671300/94153b60-46bd-11e7-8e95-e91e4020fc74.png)

That brings me to the catch statement of **Ebizmarts_MailChimp_Model_Api_Subscribers.updateSubscriber()** method and to **"else"** statement within it (because of new status is not **subscribed**).

![4](https://cloud.githubusercontent.com/assets/8599788/26671503/6c8372aa-46be-11e7-8b70-39d9144f6d6d.png)

Then i come to **Ebizmarts_MailChimp_Model_Observer.handleSubscriber()** method again and it brings me to **Ebizmarts_MailChimp_Model_Api_Subscribers.updateSubscriber()** one more time, then i get 400 API error again and the situation repeats from the very beginning again and again.

So seems that catch statement in **Ebizmarts_MailChimp_Model_Api_Subscribers.updateSubscriber()** method is incorrect and brings big problems.
Hope this will be fixed soon!

Regards, Nikolay

**Comment by durzel** [comment] 2017-06-01 09:11
Brilliant analysis.  This sounds like it could be a duplicate of #211

**Comment by elluminatte** [comment] 2017-06-01 09:43
@durzel seems you are quite right, it's already fixed in develop branch

**Closed** 2017-06-09 14:29 UTC
