### ISSUE TITLE
Orders grid filter by increment ID is broken after upgrade to 1.1.11

### ISSUE THREAD

**Issue by mmenozzi** [mailchimp/mc-magento#662] opened 2018-03-09 17:59 UTC
### Preconditions
1. Magento 1.9.3.8
2. Install this extension version 1.1.11

### Steps to reproduce
1. Go to Orders grid in admin panel
2. Filter by increment ID

### Expected result
1. Orders filtered by increment ID

### Actual result
1. Magento report page. The corresponding `var/report` file contains the following error:

```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'increment_id' in where clause is ambiguous, query was: SELECT `main_table`.*, `oe`.`mailchimp_campaign_id`, `mc`.`mailchimp_synced_flag`, `mc`.`id` FROM `sales_flat_order_grid` AS `main_table`
 LEFT JOIN `sales_flat_order` AS `oe` ON oe.entity_id=main_table.entity_id
 LEFT JOIN `mailchimp_ecommerce_sync_data` AS `mc` ON mc.related_id=main_table.entity_id AND type = 'ORD' WHERE (`increment_id` LIKE '%1271%') GROUP BY `main_table`.`entity_id` ORDER BY created_at DESC LIMIT 20
```

**Comment by m-overlund** [comment] 2018-03-09 18:03
same issue here

**Comment by m-overlund** [comment] 2018-03-09 19:41
@Santiagoebizmarts says:

You can solve this simply by removing this line in the file: 
app/code/community/Ebizmarts/MailChimp/Model/Observer.php
https://github.com/mailchimp/mc-magento/blob/1.1.11/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L498

you will need to set this value to false as well:
https://github.com/mailchimp/mc-magento/blob/1.1.11/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L457

This will be solved in the next version of course.

**Comment by Santiagoebizmarts** [comment] 2018-03-09 20:29
@mmenozzi Thanks for your feedback.
@m-overlund Thanks for the help on this. This is correct, the problem can be solved as mentioned above.

Regards.

**Comment by mmenozzi** [comment] 2018-03-12 07:15
Thank you @m-overlund.
@Santiagoebizmarts when will be released the version 1.1.13 which solves the issue?

**Comment by Santiagoebizmarts** [comment] 2018-03-12 13:26
@mmenozzi Should be out by the end of April, beginning of May.

Regards.

**Comment by mmenozzi** [comment] 2018-03-12 13:57
Sorry @Santiagoebizmarts I meant the 1.1.12 version (so the next version which should contain the fix to this issue).

**Comment by Santiagoebizmarts** [comment] 2018-03-12 14:14
@mmenozzi Yeah, that is what I understood. We will try to get it out before that but that is the limit.

**Comment by mmenozzi** [comment] 2018-03-12 17:12
So are you going to leave the order grid bug in the last "stable" version until the end of April? Is it correct?

**Comment by Santiagoebizmarts** [comment] 2018-03-12 20:53
Hello @mmenozzi 

That's the schedule, we might make a small update to solve this sooner than expected.

Regards.

**Comment by seansan** [comment] 2018-03-13 15:51
I think everyone knows what @mmenozzi is hinting at  ... this extension is the defacto solution for Magento & Mailchimp and as Mailchimp calls it "a drop in ready solution" ... 

Major release alas you can create a release schedule

Minor and urgent fixes can be released in minor versions .... (otherwise how can we call this stable if it breaks the backend?)

**Comment by Santiagoebizmarts** [comment] 2018-03-13 16:35
Hello @mmenozzi and  @seansan 

We are indeed doing this. The new release will be available really soon with the fix.

Regards.

**Closed** 2018-03-26 14:38 UTC
Labels: bug

**Comment by Santiagoebizmarts** [comment] 2018-03-27 14:54
Hello @mmenozzi 

Version 1.1.12 is already in the testing phase and should be out very soon.

Regards.

**Comment by seansan** [comment] 2018-03-27 15:27
+1 cant wait



Not using Gmelius <https://gmelius.com?ref=mail> yet?

On Tue, Mar 27, 2018 at 4:54 PM, Santiagoebizmarts <notifications@github.com

**Comment by clivewalkden** [comment] 2018-04-24 11:47
Any update on the release time for this?

**Comment by zelik888** [comment] 2018-06-14 13:50
After implementing fixes listed here, I still get this error if I try to filter by store view.

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'store_id' in where clause is ambiguous, query was: SELECT `main_table`.*, `ordersTable`.`customer_email`, `mc`.`mailchimp_synced_flag`, `mc`.`id` FROM `sales_flat_order_grid` AS `main_table` 
LEFT JOIN `sales_flat_order` AS `ordersTable` ON ordersTable.entity_id = main_table.entity_id 
LEFT JOIN `mailchimp_ecommerce_sync_data` AS `mc` ON mc.related_id=main_table.entity_id AND type = 'ORD' WHERE (`store_id` = '1') GROUP BY `main_table`.`entity_id` ORDER BY created_at DESC LIMIT 20

**Comment by Santiagoebizmarts** [comment] 2018-06-15 14:20
Hello @zelik888 ,

You can update the extension to the latest version 1.1.12 which fixes this problem.

Regards.

**Comment by zelik888** [comment] 2018-06-28 02:10
I've upgraded to latest master, 1.1.12 and the problem persists.

**Comment by Santiagoebizmarts** [comment] 2018-06-28 13:16
Hello @zelik888 

This does not happen to me in the current develop branch.
How exactly are you testing this? When you say you have version 1.1.13 what commit exactly did you download? Because it is not an official release and you might have an incomplete version.

Regards.

**Comment by zelik888** [comment] 2018-06-28 13:25
I used modman cloned from master develop branch, removed that and switched to master. It still says .13 however

**Comment by Santiagoebizmarts** [comment] 2018-06-28 13:35
Hello,

Okay, in that case let's make sure you don't have the line that was causing this problem in the past.
Please verify that the following colored lines are the same as in your site.
https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L451-L518

Regards.

**Comment by Santiagoebizmarts** [comment] 2018-06-28 13:35
@zelik888 
Forgot to mention, if you have compilation enabled in your Magento make sure to recompile.

Regards.

**Comment by zelik888** [comment] 2018-06-28 13:54
Yes, same issue. I'm on v1.1.12.1 (master) instead of develop, and the issue is the same. 

SQLSTATE[23000] [1052] Column 'store_id' in where clause is ambiguous, query was: SELECT `main_table`.*, `ordersTable`.`customer_email`, `mc`.`mailchimp_synced_flag`, `mc`.`id` FROM `sales_flat_order_grid` AS `main_table` 
LEFT JOIN `sales_flat_order` AS `ordersTable` ON ordersTable.entity_id = main_table.entity_id 
LEFT JOIN `mailchimp_ecommerce_sync_data` AS `mc` ON mc.related_id=main_table.entity_id AND type = 'ORD' WHERE (`store_id` = '1') GROUP BY `main_table`.`entity_id` ORDER BY created_at DESC LIMIT 20

**Comment by Santiagoebizmarts** [comment] 2018-06-28 17:30
Hello @zelik888 

This is a different problem because in the original post the ambiguity was found in the increment_id field.
Now that I saw your exact error I can tell this looks a lot like a conflict with another extension handling the store id as well.

In any case probably the solution for this is to remove [THIS LINE](https://github.com/mailchimp/mc-magento/blob/master/app/code/community/Ebizmarts/MailChimp/Model/Observer.php#L503).

Regards.
