### ISSUE TITLE
Product images not updating at Mailchimp

### ISSUE THREAD

**Issue by studio2f** [mailchimp/mc-magento#474] opened 2017-09-13 00:23 UTC
**Preconditions**

Magento CE 1.9.3.4 
mc-magento 1.1.8 

**Steps to reproduce**

- Create a new product that uses the Base Image default placeholder (not a unique uploaded image)
- Product syncs to MailChimp
- Upload new Base Image for Product

**Expected Result**

- Product image is updated at MailChimp

**Actual Result**

- Product does not get updated image at MailChimp
- This can be confirmed both in the MailChimp front-end and API Playground.
- Product uses MailChimp default image:

![Default image at MailChimp](https://www.joannehudson.com/mailchimp.png)

I'm really hoping we don't have to reset all ecommerce data to re-sync the product images.

**Comment by Santiagoebizmarts** [comment] 2017-09-15 16:35
Hello @studio2f 

I will test this and work in a fix if I can reproduce it. Anyways in the new version that is going to be release next week allows the resending of all ecommerce data without removing the MailChimp store allowing automations to remain working.

Kind Regards.

**Comment by Santiagoebizmarts** [comment] 2017-09-15 16:43
This seems to work correctly for me. Once I upload a new image and click Save in the product configuration the product is marked as modified and set to be uploaded in MailChimp.
Maybe the products fail after trying to be sent, you can see the modified status running the following database query:

**SELECT * FROM mailchimp_ecommerce_sync_data WHERE related_id={prod_id};**

The mailchiimp_sync_modified should be in 1 after saving the new image.

Regards.

**Comment by studio2f** [comment] 2017-09-15 17:55
mailchiimp_sync_modified is showing 0 for me.

These products were created new, and didn't have *any* images when they synced to Mailchimp the first time. A few days later, we uploaded the images. MailChimp isn't getting the uploaded image.

**Comment by Santiagoebizmarts** [comment] 2017-09-22 17:34
Hello @studio2f 
I made more testing with version 1.1.9.1 and I am not able to reproduce this problem.
Have you tried with this version?
If it continues to happen with the latest version please share more details on how you configured the extension on each scope in order to allow us to reproduce this and then fix it.
We can reopen this issue then.

Regards.

**Closed by Santiagoebizmarts** 2017-09-22 17:34 UTC

**Comment by tnethers** [comment] 2018-01-24 16:09
This doesn't seem to be fixed.

We are experiencing almost the same issue, except that the original product image folder is .../uploads/2017/11/... and the sync didn't happen until .../2018/1/... 

Mailchimp wants to use .../2017/11/...-mailchimpsuffix.jpg, but the file is inserted into .../2018/1/... This means none of our product images load.

**Comment by Santiagoebizmarts** [comment] 2018-01-24 20:57
Hello @tnethers 

This looks like the image path changed and the images were not updated in MailChimp.
If you click the button to resend ecommerce data it should trigger an update of the image paths.

You can contact our support for more help at mailchimp@ebizmarts-desk.zendesk.com.

Regards.

**Comment by tnethers** [comment] 2018-01-25 02:15
Resend did not fix.

**Comment by centerax** [comment] 2018-01-25 13:27
@tnethers see https://github.com/mailchimp/mc-magento/issues/474#issuecomment-360270682

**Comment by tnethers** [comment] 2018-01-25 14:27
I found that its only happening for the recommended products. The regular product images are correct. That said, that link #474 comment, isn't going anywhere.

**Comment by centerax** [comment] 2018-01-25 14:30
You can contact our support for more help at mailchimp@ebizmarts-desk.zendesk.com.

**Comment by tnethers** [comment] 2018-01-25 14:31
Aye, did thanks! Someone replied.
