### ISSUE TITLE
When MailChimp site is down failures occur in the extension.

### ISSUE THREAD

**Issue by Santiagoebizmarts** [mailchimp/mc-magento#815] opened 2018-11-01 17:35 UTC
### Preconditions

1. MailChimp for Magento 1.1.12
2. Magento 1.9.3.9

### Steps to reproduce

1. Access the site when MailChimp API is down.

### Expected result

1. Page works as expected except the MailChimp features that are expected to fail if the API is down.
Should send everything okay once the API gets back up.

### Actual result

1. Failures start occurring for example when retrieving the mc.js file.

**Comment by alexjamesbrown** [comment] 2018-11-02 12:46
+1 for this!
I actually came here to open the same issue.

During the large outage yesterday, our site was knocked offline until we disabled this extension.
It's extremely tightly coupled to the availability of the Mailchimp API

**Comment by alexjamesbrown** [comment] 2018-11-02 18:46
The whole apache process failed.
according to new relic, it looks like several routes, including

/customer/account/login
/catalog/product/view
/catalog/category/view

...have a direct dependency on the  us12.api.mailchimp.com api which was down, so were waiting for it to respond.

**Comment by Santiagoebizmarts** [comment] 2018-11-02 20:00
Thank you very much @alexjamesbrown 

This is very useful information. We will start testing those views.

Regards.

**Comment by alexjamesbrown** [comment] 2018-11-03 00:30
@Santiagoebizmarts no problem, let me know if I can help any more!

**Comment by gonzaloebiz** [comment] 2018-11-14 18:57
@alexjamesbrown 

you remember what was the result? A page with a 504? We are trying to reproduce internally

Best

**Comment by alexjamesbrown** [comment] 2018-11-16 19:55
![image](https://user-images.githubusercontent.com/437743/48644068-71218f80-e9d9-11e8-8cc0-8a3caee10347.png)

These routes were left waiting:

![image](https://user-images.githubusercontent.com/437743/48644085-7da5e800-e9d9-11e8-879f-7bc15f5bbed5.png)

I guess the concern is why are those routes awaiting a 3rd party api

**Comment by dbashyal** [comment] 2018-11-21 04:46
FYI - We also encountered Apache server error at the same time as OP. We didn't know what was wrong until we found this thread. Based on hosting provider website returned "http 403 forbidden" and loaded apache default test page instead of our website. Before we figured out what was going on, it fixed by itself. Probably mailchimp was back online and the issue was fixed.

**Closed** 2018-11-27 14:51 UTC
Labels: bug, priority

**Comment by alexjamesbrown** [comment] 2018-11-27 15:36
@ebizmarts-keller has this been released?
https://github.com/mailchimp/mc-magento/releases is showing latest release as May?

**Comment by ebizmarts-keller** [comment] 2018-11-27 16:38
@alexjamesbrown we are on testing phase for version 1.1.13 as of now, it will be released in a few days (might take longer in the marketplace but will be much sooner in the repository)

**Comment by alexjamesbrown** [comment] 2018-12-03 15:34
@ebizmarts-keller has this been released??
Mailchimp is once again down (right now) and took our site offline **again**

**Comment by Santiagoebizmarts** [comment] 2018-12-03 16:44
Hello @alexjamesbrown 
You can see the full change at https://github.com/mailchimp/mc-magento/commit/36564954b36787b601cfad55d6e1892536c74530

Regards.

**Comment by alexjamesbrown** [comment] 2018-12-03 17:36
@Santiagoebizmarts thanks, any idea when a 'proper' release will be released?

**Comment by dbolufer** [comment] 2018-12-03 18:14
@Santiagoebizmarts In my opinion your changes only patches the problem. If the Mailchimp API is down, our magentos is 20 sg slower.

Are you thinking to change the way you connect to the API to make this asynchronous?

**Comment by dbolufer** [comment] 2018-12-03 19:46
Yes, that is the problem! But as @alexjamesbrown has said, Why do you instance the mailchimp API on /catalog/product/view and /catalog/category/view?

Anyway, I think in this line you should add the timeout too https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L1088

**Comment by Santiagoebizmarts** [comment] 2018-12-03 20:38
Hello @dbolufer 

The timeout will be used in any call to MailChimp API. It is handled in the library and all the calls made to MailChimp go through it.

Regards.
