### ISSUE TITLE
Can't change attribute or status of multiple products

### ISSUE THREAD

**Issue by tomlankhorst** [mailchimp/mc-magento#241] opened 2017-05-14 20:04 UTC
Preconditions
====
- Magento CE 1.9.3.2
- mc-magento 1.16

Steps to reproduce
=====
- Products are selected in admin's product grid
- Product status is changed or attributes changed

**Expected**
Products status or attributes changed
**Actual**
Empty error message occurs

![image](https://cloud.githubusercontent.com/assets/675432/26037333/240b19e0-38f1-11e7-90e3-5adcc5cbb6a3.png)

Additional Info
====
Seems that there is something going wrong in the attribute-changed observer. The log file 'observer.log' contains:

```
... more lines ...
2017-05-14T20:03:00+00:00 DEBUG (7): Ebizmarts_MailChimp_Model_Observer::productAttributeUpdate
2017-05-14T20:03:00+00:00 DEBUG (7): 0
```

**Comment by centerax** [comment] 2017-05-16 10:38
@tomlankhorst we have identified the problem. the fix is on its wat.

**Comment by yoosefi** [comment] 2017-05-18 21:57
This is a duplicate of #209

**Closed** 2017-06-01 19:45 UTC
Labels: bug, done
