### ISSUE TITLE
Add the options to resend all the ecommerce data or resend only the products, customers, orders or quotes

### ISSUE THREAD

**Issue by luciaebizmarts** [mailchimp/mc-magento#891] opened 2019-02-22 13:37 UTC
Mailchimp for Magento development version
 Magento any version

When click on the button resend ecommerce data add the option to send only the products, customers, orders or quotes and on the notification after flush image product cache on the link to resend ecommerce data mark by default only the option resend products.

**Comment by giorello** [comment] 2019-05-13 11:50
Merged in PR #945.

**Comment by Santiagoebizmarts** [comment] 2019-05-31 18:19
Preconditions
Error introduced in this fix.

Steps to reproduce
Run phpunit tests from php 7.2
Expected result
Test run with success.
Actual result
Error thrown due to missing arguments on functions:
https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L1038
https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L1042
https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L1046
https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L1050
https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L1054

**Comment by Santiagoebizmarts** [comment] 2019-06-03 18:49
Move functinon [deleteFlushMagentoCacheFlag](https://github.com/mailchimp/mc-magento/blob/develop/app/code/community/Ebizmarts/MailChimp/Helper/Data.php#L4117) to be called when products are set to be resend.

**Comment by Santiagoebizmarts** [comment] 2019-06-06 21:15
When going to System -> Cache Management and clicking Flush Catalog Images Cache button a notification is displayed informing that products should be resent. Link in notification not working.

**Closed** 2019-06-07 20:12 UTC
Labels: done, enhancement
