### ISSUE TITLE
MailChimp issues related to cron job

### ISSUE THREAD

**Issue by bijugit** [mailchimp/mc-magento#356] opened 2017-07-03 05:44 UTC
Hi,

MailChimp jobs stop the generation of sitemap as well as google feed generation.If  we disable the module and tested the sitemap & google feed generation through cron and it is working fine.

Please give your feedback as soon as possible..

Regards,

**Comment by ebizmarts-keller** [comment] 2017-07-03 19:10
Hello, 

Thanks for submitting the issue

Adding your versions from the ticket in Zendesk:

> Magento ver is :  1.9.2.4
> MailChimp For Magento v1.1.7

Someone will look at this

Regards

**Comment by bijugit** [comment] 2017-07-04 11:42
Hi,

Thanks for your reply,

Can you replicate this issue from in your side?

Please give your valid feedback as soon as possible.

Thanks in advance.

**Comment by bijugit** [comment] 2017-07-05 06:09
Hi,

Can replicate the issue from in your end?

Please give your valid feedback as soon as possible.

Regards,

**Comment by bijugit** [comment] 2017-07-06 12:54
Hi,

Can you please give your valid reply as soon as possible.

Regards,

**Comment by ebizmarts-keller** [comment] 2017-07-06 13:57
Hello, 

We are still looking into it, maybe today or tomorrow we'll see if we can find the issue.

**Comment by burningfish** [comment] 2017-07-19 16:04
Hi Ebizmarts,

Related to this issue, I believe there is a bug related to the `mailchimp_process_webhook_data` cron job.

In the Ebizmarts_MailChimp_Model_ProcessWebhook::processWebhookData function it looks like there should be restriction to only process webhook requests that have not already been processed. It doesn't seem like these requests should be processed multiple times. Once they are marked as processed, it seems like they should not be processed again.

Adding a filter the collection to restrict it to only unprocessed requests is the simple fix I have put in place for our store:
```
        $collection = Mage::getResourceModel('mailchimp/webhookrequest_collection')
            ->addFieldToFilter("processed", array(0));
```

Without this filter, the entire collection gets processed on every run. Before I added this fix, this job was taking longer and longer on each run to the point that it was taking over 25 minutes to complete.

Cheers,
Dave

**Comment by ebizmarts-keller** [comment] 2017-07-20 17:49
Hello @burningfish 

Thank you very much for the input.

We are aware of this actually, we added a batch limit for the webhook cronjob and the filter a while ago, but this was after version 1.1.7 was released, the fix will be included in version 1.1.8.

This is the commit I was just referring to that should solve the problem as well: https://github.com/mailchimp/mc-magento/commit/67f184dc4a5359920c6cd43dbf7a6cf0d96ea5ed

Not sure if it is related to this issue with the Google Sitemaps though, can you confirm if it is related and/or solves that issue?

**Comment by burningfish** [comment] 2017-07-20 17:56
Thanks for you prompt reply `ebizmarts-keller`.
Glad to hear that a fix is already in place for the next version!

Personally, we have not had issues with the Sitemap generation but we did put in this fix for the long running `mailchimp_process_webhook_data`. Any long running jobs in the Magento cron can block other jobs, like the sitemap generation and I'm not sure if this long running job `mailchimp_process_webhook_data` is the cause of `bijugit`'s issues or not but it is one possible cause I thought I would suggest.

**Comment by punkstar** [comment] 2017-07-24 10:32
Thanks for the solution @burningfish - we're using that patch in production without issue.  I agree that this job blocking up the cron queue is almost certainly what was @bijugit's problem with sitemap / feed generation.

I think this can be closed @ebizmarts-keller! 🎉

**Closed** 2017-07-25 19:54 UTC
